
#  > This is a Docker Compose file for a DEVEL/DEBUG setup
#  *** DO NOT USE THIS IN PRODUCTION IT IS VERY INSECURE ***
#

version: '2'

services:

  sql:
    image: postgres:latest
    environment:
      - POSTGRES_DB=xsshunter
      - POSTGRES_USER=xsshunter
      - POSTGRES_PASSWORD=badpassword
    ports:
      - "5432:5432"

  api:
    build: ./api/
    environment:
      - XSSHUNTER_LISTEN_PORT=8888
      - XSSHUNTER_DEBUG=1
      - XSSHUNTER_COOKIE_SECRET=badsecret
    expose:
      - "8888"
    depends_on:
      - sql

  web:
    build: ./gui/
    volumes:
      - ./gui/ssl:/var/ngix/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
